import PDFDocument from 'pdfkit';
import { Response } from 'express';
import { format } from 'date-fns';

const REPORT_VERSION = 'v1.0';
const CRM_NAME = 'Zolvex CRM';

export interface ExportMeta {
  title: string;
  generatedBy: string;
  generatedAt: Date;
  timezone: string;
  filters: Record<string, any>;
  version?: string;
}

// Build a descriptive filename: e.g. "financial-report-2026-07-11"
export const buildFilename = (domain: string): string => {
  const dateStr = format(new Date(), 'yyyy-MM-dd');
  return `${domain}-report-${dateStr}`;
};

// Escape a CSV cell value (handle commas, quotes, newlines)
const escapeCell = (val: any): string => {
  const str = val === null || val === undefined ? '' : String(val);
  // If the value contains comma, quote, or newline — wrap in quotes and escape inner quotes
  if (str.includes(',') || str.includes('"') || str.includes('\n') || str.includes('₹')) {
    return `"${str.replace(/"/g, '""')}"`;
  }
  return str;
};

// Format filter description for metadata
const formatFilters = (filters: Record<string, any>): string => {
  const parts: string[] = [];
  if (filters.start_date) parts.push(`From: ${format(new Date(filters.start_date), 'dd MMM yyyy')}`);
  if (filters.end_date) parts.push(`To: ${format(new Date(filters.end_date), 'dd MMM yyyy')}`);
  if (filters.city_id) parts.push(`City: ${filters.city_id}`);
  if (parts.length === 0) parts.push('All Time');
  return parts.join(' | ');
};

// -----------------------------------------------------------------------
// CSV Generator
// -----------------------------------------------------------------------
export const generateCSV = (
  res: Response,
  domain: string,
  meta: ExportMeta,
  headers: string[],
  rows: any[][]
) => {
  const filename = buildFilename(domain);
  const version = meta.version || REPORT_VERSION;

  // UTF-8 BOM prefix ensures Excel opens the file with correct encoding (including ₹ symbol)
  const BOM = '\uFEFF';

  const metaRows = [
    `Report,${escapeCell(meta.title)}`,
    `Generated By,${escapeCell(meta.generatedBy)}`,
    `Generated At,${escapeCell(format(meta.generatedAt, "dd MMM yyyy 'at' HH:mm 'UTC'"))}`,
    `Timezone,${escapeCell(meta.timezone)}`,
    `Filters,${escapeCell(formatFilters(meta.filters))}`,
    `Version,${escapeCell(version)}`,
    `CRM,${escapeCell(CRM_NAME)}`,
    '', // blank separator row
  ];

  const dataRows = rows.length > 0
    ? rows.map(row => row.map(escapeCell).join(','))
    : ['(No records found for the selected filters)'];

  const csvContent = BOM + [
    ...metaRows,
    headers.map(escapeCell).join(','),
    ...dataRows,
  ].join('\n');

  res.setHeader('Content-Type', 'text/csv; charset=utf-8');
  res.setHeader('Content-Disposition', `attachment; filename="${filename}.csv"`);
  res.send(csvContent);
};

// -----------------------------------------------------------------------
// PDF Generator
// -----------------------------------------------------------------------
const PAGE_MARGIN = 50;
const ROW_HEIGHT = 22;
const HEADER_HEIGHT = 20;

const drawTableHeader = (doc: any, headers: string[], colWidth: number, y: number) => {
  doc.font('Helvetica-Bold').fontSize(9).fillColor('#374151');
  headers.forEach((h, i) => {
    doc.text(h, PAGE_MARGIN + i * colWidth, y, { width: colWidth - 4, align: 'left' });
  });
  doc
    .strokeColor('#d1d5db')
    .lineWidth(1)
    .moveTo(PAGE_MARGIN, y + HEADER_HEIGHT)
    .lineTo(doc.page.width - PAGE_MARGIN, y + HEADER_HEIGHT)
    .stroke();
};

export const generatePDF = (
  res: Response,
  domain: string,
  meta: ExportMeta,
  headers: string[],
  rows: any[][]
) => {
  const filename = buildFilename(domain);
  const version = meta.version || REPORT_VERSION;

  res.setHeader('Content-Type', 'application/pdf');
  res.setHeader('Content-Disposition', `attachment; filename="${filename}.pdf"`);

  const doc = new PDFDocument({ margin: PAGE_MARGIN, size: 'A4', bufferPages: true });
  doc.pipe(res);

  const usableWidth = doc.page.width - PAGE_MARGIN * 2;
  const colWidth = usableWidth / headers.length;

  // ---- Title block ----
  doc.fontSize(18).font('Helvetica-Bold').fillColor('#111827')
    .text(`${CRM_NAME}`, { align: 'center' });
  doc.fontSize(13).font('Helvetica').fillColor('#374151')
    .text(meta.title, { align: 'center' });
  doc.moveDown(0.5);

  // ---- Meta block ----
  doc.fontSize(8).fillColor('#6b7280');
  const metaLine1 = `Generated by: ${meta.generatedBy}   |   ${format(meta.generatedAt, "dd MMM yyyy 'at' HH:mm 'UTC'")}   |   Timezone: ${meta.timezone}`;
  const metaLine2 = `Filters: ${formatFilters(meta.filters)}   |   Version: ${version}`;
  doc.text(metaLine1, PAGE_MARGIN, doc.y, { align: 'center', width: usableWidth });
  doc.text(metaLine2, PAGE_MARGIN, doc.y + 2, { align: 'center', width: usableWidth });

  doc.moveDown(1.5);

  // ---- Separator ----
  doc.strokeColor('#e5e7eb').lineWidth(1)
    .moveTo(PAGE_MARGIN, doc.y)
    .lineTo(doc.page.width - PAGE_MARGIN, doc.y)
    .stroke();
  doc.moveDown(0.5);

  // ---- Table ----
  const tableStartY = doc.y;
  drawTableHeader(doc, headers, colWidth, tableStartY);

  let y = tableStartY + HEADER_HEIGHT + 6;

  if (rows.length === 0) {
    doc.font('Helvetica').fontSize(10).fillColor('#9ca3af')
      .text('No records found for the selected filters.', PAGE_MARGIN, y, { align: 'center', width: usableWidth });
  } else {
    doc.font('Helvetica').fontSize(9).fillColor('#111827');
    rows.forEach((row, rowIdx) => {
      // Page break — re-draw header on new page
      if (y > doc.page.height - PAGE_MARGIN - ROW_HEIGHT * 2) {
        doc.addPage();
        y = PAGE_MARGIN;
        drawTableHeader(doc, headers, colWidth, y);
        y += HEADER_HEIGHT + 6;
        doc.font('Helvetica').fontSize(9).fillColor('#111827');
      }

      // Alternating row background
      if (rowIdx % 2 === 0) {
        doc.rect(PAGE_MARGIN, y - 3, usableWidth, ROW_HEIGHT)
          .fill('#f9fafb');
        doc.fillColor('#111827');
      }

      row.forEach((cell, j) => {
        doc.text(String(cell ?? ''), PAGE_MARGIN + j * colWidth, y, {
          width: colWidth - 4,
          align: 'left',
          ellipsis: true,
        });
      });

      y += ROW_HEIGHT;
    });
  }

  // ---- Page numbers (added after bufferPages) ----
  const totalPages = doc.bufferedPageRange().count;
  for (let i = 0; i < totalPages; i++) {
    doc.switchToPage(i);
    doc.fontSize(7).fillColor('#9ca3af')
      .text(
        `Page ${i + 1} of ${totalPages}   |   ${CRM_NAME}   |   Confidential`,
        PAGE_MARGIN,
        doc.page.height - 30,
        { align: 'center', width: usableWidth }
      );
  }

  doc.end();
};
